### ISSUE TITLE
`consolidate` in `component-compiler-utils` has already handled template engines

### ISSUE THREAD

**Issue by JounQin** [yyx990803/pug-plain-loader#1]
Is it really needed for vue-loader@15?

``` js
{
  test: /\.pug$/,
  use: ['html-loader', 'pug-html-loader'], // whatever
  exclude: /\.vue$/
}
```

https://github.com/vuejs/vue-loader/pull/1215

**Comment by yyx990803** [comment]
Using loaders is more flexible because it allows you to pass explicit options for different preprocessors.
