### ISSUE TITLE
Feature request. Please add an option "root"

### ISSUE THREAD

**Issue by dev-natalya** [yyx990803/pug-plain-loader#2]
Please refer to https://github.com/pugjs/pug-loader/issues/96#issuecomment-385123359

It would be great to be able to get rid of the relative paths, having at least one alias and in this case, at least to be able to set the root path.

If possible, please add an ability to handle webpack's aliases as well.

Thank you!

**Comment by dev-natalya** [comment]
I apologize, there is a `basedir` option that does the same thing

**Comment by printjs** [comment]
@natalya-kim I have used `basedir`,but I can't resolve the problm
```js
        {
            test: /\.pug$/,
            use: [
                "raw-loader",
                {
                    loader: "pug-plain-loader",
                    options: {
                        basedir: join(__dirname, "src/resource/templates"),
                    }
                },
            ],
        },
```

**Comment by printjs** [comment]
@yyx990803
