### ISSUE TITLE
unexpected token "indent"

### ISSUE THREAD

**Issue by heartz66** [yyx990803/pug-plain-loader#6]
Unable to compile after upgrading to `vue@2.5.18` and `vue-template-compiler@2.5.18`

![66fc439155ac96a034e1de1c07c9bdc4](https://user-images.githubusercontent.com/8833887/49685333-3693aa00-fae2-11e8-8818-7c6773122a14.png)

**Comment by yyx990803** [comment]
Tracked in https://github.com/vuejs/vue/issues/9169
